#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

docker rmi $(docker images -q -f dangling=true) || echo "No dangling images."
docker rm $(docker ps -aq -f status=exited) || echo "No stale containers."
