#!/bin/sh

# Create a database backup.
#
# Usage:
#     $ docker-compose run --rm db backup

set -o errexit
set -o pipefail
set -o nounset

echo "Backing up database: '${POSTGRES_DB}'"

export PGPASSWORD="${POSTGRES_PASSWORD}"

backup_filename="DB_$(date +'%Y_%m_%dT%H_%M_%S').sql.gz"
pg_dump \
    --host=${POSTGRES_HOST} \
    --port=${POSTGRES_PORT} \
    --dbname="${POSTGRES_DB}" \
    --username="${POSTGRES_USER}" \
    | gzip > "/backups/${backup_filename}"

echo "'${POSTGRES_DB}' database backup '${backup_filename}' has been created and placed in '/backups'."
