#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

script_parent=$(cd $(dirname ${BASH_SOURCE}) && pwd -P)
scripts_root=$(cd $(dirname ${script_parent}) && pwd -P)
project_root=$(cd $(dirname ${scripts_root}) && pwd -P)

# Check env files
${project_root}/scripts/setup/init-env

# Start containers
echo "Running tests"

docker-compose -f ${project_root}/docker-compose.test.yml up -d --build

# Run tests
docker-compose -f ${project_root}/docker-compose.test.yml run --rm web python scripts/runtests.py --coverage

# Cleanup stale images/containers
docker-compose -f ${project_root}/docker-compose.test.yml down
${project_root}/scripts/util/cleanup
