#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

script_parent=$(cd $(dirname ${BASH_SOURCE}) && pwd -P)
scripts_root=$(cd $(dirname ${script_parent}) && pwd -P)
project_root=$(cd $(dirname ${scripts_root}) && pwd -P)

set -a

for env in ".db.env" ".proxy.env" ".rabbitmq.env" ".redis.env" ".web.env"; do
  source "${project_root}/.envs/${env}"
  echo " Set env file: ${env}"
done

echo "Set all env files."
